# Generated by Django 4.0.6 on 2022-07-05 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='가계부 제목')),
                ('balance', models.IntegerField(default=0, verbose_name='가계부 시작 금액')),
                ('is_delete', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_book', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountBookRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(verbose_name='금액')),
                ('memo', models.CharField(max_length=100, verbose_name='메모')),
                ('is_delete', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('account_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_book_record', to='account_book.accountbook', verbose_name='가계부')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
