# Generated by Django 4.0.6 on 2022-07-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbook',
            old_name='is_delete',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='accountbookrecord',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
