# Generated by Django 4.0.6 on 2022-07-08 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account_book', '0002_rename_is_delete_accountbook_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbook',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='삭제시간'),
        ),
        migrations.AddField(
            model_name='accountbookrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountbookrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='삭제시간'),
        ),
    ]
